image: ubuntu:latest

stages:
  - build

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

build:
  stage: build
  script:
    - echo "Start building"
    - mvn clean verify


