image: maven:3.8.4-jdk-8

stages:
  - build

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

build:
  stage: build
  script:
    - echo "Start building"
    - mvn clean verify
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml


